# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('area', models.CharField(choices=[('Westlands', 'Westlands Constituency'), ('Dagoretti', 'Dagoretti Constituency'), ('Langata', 'Langata Constituency'), ('Kasarani', 'Kasarani Constituency'), ('Embakasi', 'Embakasi Constituency'), ('Starehe', 'Starehe Constituency'), ('Kamkunji', 'Kamkunji Constituency')], max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='decription',
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=True, upload_to='index/'),
        ),
    ]
